// Build-time harvester: runs hamlib's rigctl across every rig model and generates
// the pure-C# RigDatabase for MultiCat.Hamlib. MultiCAT ships no native hamlib —
// only the knowledge extracted here. Rerun when a new hamlib release lands:
//
//   dotnet run --project tools/HamlibHarvest -- <path-to-rigctl.exe> src/MultiCat.Hamlib/RigDatabase.g.cs

using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;

if (args.Length != 2)
{
    Console.Error.WriteLine("usage: HamlibHarvest <rigctl.exe> <output.g.cs>");
    return 1;
}

var rigctl = args[0];
var outputPath = args[1];

var listOutput = await RunAsync(rigctl, "-l");
var ids = new List<int>();
foreach (var line in listOutput.Split('\n'))
{
    var match = Regex.Match(line, @"^\s*(\d+)\s+\S");
    if (match.Success)
    {
        ids.Add(int.Parse(match.Groups[1].Value));
    }
}

Console.WriteLine($"found {ids.Count} rig models, dumping caps…");

var rigs = new List<(int Id, string Mfg, string Model, string Status, string PortType, int SpeedMin, int SpeedMax, string SerialConfig, string Handshake)>();
string? hamlibVersion = null;

foreach (var id in ids)
{
    var caps = await RunAsync(rigctl, $"-m {id} -u");
    var model = Field(caps, "Model name");
    var mfg = Field(caps, "Mfg name");
    if (model is null || mfg is null)
    {
        Console.WriteLine($"  skipping {id}: no caps");
        continue;
    }

    hamlibVersion ??= Regex.Match(caps, @"Hamlib version:\s*Hamlib\s+(\S+)").Groups[1].Value;

    var speed = Regex.Match(caps, @"Serial speed:\s*(\d+)\.\.(\d+)\s*baud,\s*(\S+?),\s*ctrl=(\S+)");
    rigs.Add((
        id, mfg, model,
        Field(caps, "Backend status") ?? "Unknown",
        Field(caps, "Port type") ?? "Unknown",
        speed.Success ? int.Parse(speed.Groups[1].Value) : 0,
        speed.Success ? int.Parse(speed.Groups[2].Value) : 0,
        speed.Success ? speed.Groups[3].Value : "",
        speed.Success ? speed.Groups[4].Value : ""));
}

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated>");
sb.AppendLine($"// Rig capability database harvested from Hamlib {hamlibVersion} by tools/HamlibHarvest");
sb.AppendLine("// (rigctl --dump-caps, per model). Do not edit by hand; rerun the harvester instead.");
sb.AppendLine("//");
sb.AppendLine("// Data derived from the Hamlib project - https://hamlib.github.io");
sb.AppendLine("// Copyright (C) Hamlib contributors, licensed LGPL-2.1-or-later.");
sb.AppendLine("// To the extent this compilation of rig data is protected, it is redistributed");
sb.AppendLine("// within this GPLv3 project as permitted by LGPL 2.1 section 3.");
sb.AppendLine("// </auto-generated>");
sb.AppendLine();
sb.AppendLine("namespace MultiCat.Hamlib;");
sb.AppendLine();
sb.AppendLine("public static partial class RigDatabase");
sb.AppendLine("{");
sb.AppendLine($"    public const string HamlibVersion = \"{hamlibVersion}\";");
sb.AppendLine();
sb.AppendLine("    public static IReadOnlyList<RigModel> All { get; } =");
sb.AppendLine("    [");
foreach (var r in rigs.OrderBy(r => r.Id))
{
    sb.AppendLine(
        $"        new({r.Id}, {Quote(r.Mfg)}, {Quote(r.Model)}, {Quote(r.Status)}, {Quote(r.PortType)}, " +
        $"{r.SpeedMin}, {r.SpeedMax}, {Quote(r.SerialConfig)}, {Quote(r.Handshake)}),");
}

sb.AppendLine("    ];");
sb.AppendLine("}");

File.WriteAllText(outputPath, sb.ToString());
Console.WriteLine($"wrote {rigs.Count} rigs (hamlib {hamlibVersion}) to {outputPath}");
return 0;

static string? Field(string caps, string name)
{
    var match = Regex.Match(caps, $@"^{Regex.Escape(name)}:\s*(.+?)\s*$", RegexOptions.Multiline);
    return match.Success ? match.Groups[1].Value.Trim() : null;
}

static string Quote(string s) => $"\"{s.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";

static async Task<string> RunAsync(string exe, string arguments)
{
    var psi = new ProcessStartInfo
    {
        FileName = exe,
        Arguments = arguments,
        RedirectStandardOutput = true,
        RedirectStandardError = true,
        UseShellExecute = false,
        CreateNoWindow = true,
    };
    using var process = Process.Start(psi)!;
    var output = await process.StandardOutput.ReadToEndAsync();
    await process.WaitForExitAsync();
    return output;
}
